name: ""
title: Do Mistakes Matter?


remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
    - navigation.sections

header_pages:
  - about.md

social_links:
  - { platform: github,         user_url: "https://github.com/jekyll/minima" }
