title: Do Mistakes Matter? Comparing Trust Responses of Different Age Groups to Errors Made by Physically Assistive Robots

theme: minima

header_pages:
  - about.md

social_links:
  - { platform: github,         user_url: "https://github.com/jekyll/minima" }
